# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CutSPR(object):
    def setupUi(self, CutSPR):
        CutSPR.setObjectName("CutSPR")
        CutSPR.resize(823, 949)
        self.centralwidget = QtWidgets.QWidget(CutSPR)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.IntroductionPage = QtWidgets.QWidget()
        self.IntroductionPage.setMaximumSize(QtCore.QSize(800, 16777215))
        self.IntroductionPage.setObjectName("IntroductionPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.IntroductionPage)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.IntroductionPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 130))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_7.addWidget(self.textBrowser)
        self.sgRNAHeader = CQlabel(self.IntroductionPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sgRNAHeader.sizePolicy().hasHeightForWidth())
        self.sgRNAHeader.setSizePolicy(sizePolicy)
        self.sgRNAHeader.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.sgRNAHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sgRNAHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.sgRNAHeader.setObjectName("sgRNAHeader")
        self.verticalLayout_7.addWidget(self.sgRNAHeader)
        self.sgRNAdesc = QtWidgets.QTextBrowser(self.IntroductionPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.sgRNAdesc.sizePolicy().hasHeightForWidth())
        self.sgRNAdesc.setSizePolicy(sizePolicy)
        self.sgRNAdesc.setMaximumSize(QtCore.QSize(16777215, 140))
        self.sgRNAdesc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sgRNAdesc.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sgRNAdesc.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.sgRNAdesc.setObjectName("sgRNAdesc")
        self.verticalLayout_7.addWidget(self.sgRNAdesc)
        self.indelCassHeader = CQlabel(self.IntroductionPage)
        self.indelCassHeader.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.indelCassHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.indelCassHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.indelCassHeader.setObjectName("indelCassHeader")
        self.verticalLayout_7.addWidget(self.indelCassHeader)
        self.indelCassDesc = QtWidgets.QTextBrowser(self.IntroductionPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indelCassDesc.sizePolicy().hasHeightForWidth())
        self.indelCassDesc.setSizePolicy(sizePolicy)
        self.indelCassDesc.setMaximumSize(QtCore.QSize(16777215, 150))
        self.indelCassDesc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.indelCassDesc.setFrameShadow(QtWidgets.QFrame.Plain)
        self.indelCassDesc.setObjectName("indelCassDesc")
        self.verticalLayout_7.addWidget(self.indelCassDesc)
        self.vecConstHeader = CQlabel(self.IntroductionPage)
        self.vecConstHeader.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.vecConstHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vecConstHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.vecConstHeader.setObjectName("vecConstHeader")
        self.verticalLayout_7.addWidget(self.vecConstHeader)
        self.vecConstDesc = QtWidgets.QTextBrowser(self.IntroductionPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vecConstDesc.sizePolicy().hasHeightForWidth())
        self.vecConstDesc.setSizePolicy(sizePolicy)
        self.vecConstDesc.setMaximumSize(QtCore.QSize(16777215, 130))
        self.vecConstDesc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.vecConstDesc.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vecConstDesc.setObjectName("vecConstDesc")
        self.verticalLayout_7.addWidget(self.vecConstDesc)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.label_29 = QtWidgets.QLabel(self.IntroductionPage)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_7.addWidget(self.label_29)
        self.label_31 = QtWidgets.QLabel(self.IntroductionPage)
        self.label_31.setOpenExternalLinks(True)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_7.addWidget(self.label_31)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.IntroductionPage, "")
        self.gsRNAsearch = QtWidgets.QWidget()
        self.gsRNAsearch.setObjectName("gsRNAsearch")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gsRNAsearch)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.gsRNAsearch)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileSelectionButton = QtWidgets.QPushButton(self.gsRNAsearch)
        self.fileSelectionButton.setObjectName("fileSelectionButton")
        self.horizontalLayout.addWidget(self.fileSelectionButton)
        self.refGenFiles = QtWidgets.QListWidget(self.gsRNAsearch)
        self.refGenFiles.setMaximumSize(QtCore.QSize(16777215, 40))
        self.refGenFiles.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.refGenFiles.setObjectName("refGenFiles")
        self.horizontalLayout.addWidget(self.refGenFiles)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.gsRNAsearch)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.deletionTargetSeq = QtWidgets.QPlainTextEdit(self.gsRNAsearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deletionTargetSeq.sizePolicy().hasHeightForWidth())
        self.deletionTargetSeq.setSizePolicy(sizePolicy)
        self.deletionTargetSeq.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.deletionTargetSeq.setFont(font)
        self.deletionTargetSeq.setObjectName("deletionTargetSeq")
        self.horizontalLayout_2.addWidget(self.deletionTargetSeq)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.gsRNAsearch)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.PAMpattern = QtWidgets.QLineEdit(self.gsRNAsearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PAMpattern.sizePolicy().hasHeightForWidth())
        self.PAMpattern.setSizePolicy(sizePolicy)
        self.PAMpattern.setMaximumSize(QtCore.QSize(100, 20))
        self.PAMpattern.setMaxLength(3)
        self.PAMpattern.setObjectName("PAMpattern")
        self.verticalLayout_3.addWidget(self.PAMpattern)
        self.label_30 = QtWidgets.QLabel(self.gsRNAsearch)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_3.addWidget(self.label_30)
        self.targetLength = QtWidgets.QLineEdit(self.gsRNAsearch)
        self.targetLength.setMaximumSize(QtCore.QSize(100, 16777215))
        self.targetLength.setObjectName("targetLength")
        self.verticalLayout_3.addWidget(self.targetLength)
        spacerItem1 = QtWidgets.QSpacerItem(20, 140, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cutRun = QtWidgets.QPushButton(self.gsRNAsearch)
        self.cutRun.setEnabled(False)
        self.cutRun.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cutRun.setObjectName("cutRun")
        self.verticalLayout_4.addWidget(self.cutRun)
        self.label_2 = QtWidgets.QLabel(self.gsRNAsearch)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_43 = QtWidgets.QLabel(self.gsRNAsearch)
        self.label_43.setMaximumSize(QtCore.QSize(10000000, 16777215))
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_6.addWidget(self.label_43)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_42 = QtWidgets.QLabel(self.gsRNAsearch)
        self.label_42.setMaximumSize(QtCore.QSize(240, 16777215))
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_6.addWidget(self.label_42)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.label_45 = QtWidgets.QLabel(self.gsRNAsearch)
        self.label_45.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_6.addWidget(self.label_45)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.resultsList = QtWidgets.QListWidget(self.gsRNAsearch)
        self.resultsList.setMovement(QtWidgets.QListView.Static)
        self.resultsList.setObjectName("resultsList")
        self.verticalLayout_4.addWidget(self.resultsList)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cloningSitesgRNA = QtWidgets.QPushButton(self.gsRNAsearch)
        self.cloningSitesgRNA.setEnabled(False)
        self.cloningSitesgRNA.setObjectName("cloningSitesgRNA")
        self.horizontalLayout_3.addWidget(self.cloningSitesgRNA)
        self.label_27 = QtWidgets.QLabel(self.gsRNAsearch)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_3.addWidget(self.label_27)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.gsRNAsearch, "")
        self.cassetteDesign = QtWidgets.QWidget()
        self.cassetteDesign.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cassetteDesign.setFont(font)
        self.cassetteDesign.setStyleSheet("")
        self.cassetteDesign.setObjectName("cassetteDesign")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.cassetteDesign)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.cassetteDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 15))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.insertSeq = QtWidgets.QTextEdit(self.cassetteDesign)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertSeq.sizePolicy().hasHeightForWidth())
        self.insertSeq.setSizePolicy(sizePolicy)
        self.insertSeq.setMinimumSize(QtCore.QSize(0, 200))
        self.insertSeq.setMaximumSize(QtCore.QSize(16777215, 200))
        self.insertSeq.setObjectName("insertSeq")
        self.verticalLayout_6.addWidget(self.insertSeq)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_6.addLayout(self.verticalLayout_12)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cloningSiteRecomb = QtWidgets.QPushButton(self.cassetteDesign)
        self.cloningSiteRecomb.setEnabled(True)
        self.cloningSiteRecomb.setObjectName("cloningSiteRecomb")
        self.horizontalLayout_4.addWidget(self.cloningSiteRecomb)
        self.label_28 = QtWidgets.QLabel(self.cassetteDesign)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_4.addWidget(self.label_28)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.label_32 = QtWidgets.QLabel(self.cassetteDesign)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.flankBSize = QtWidgets.QLineEdit(self.cassetteDesign)
        self.flankBSize.setMaximumSize(QtCore.QSize(100, 20))
        self.flankBSize.setCursorPosition(3)
        self.flankBSize.setObjectName("flankBSize")
        self.gridLayout.addWidget(self.flankBSize, 1, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.cassetteDesign)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 0, 1, 1, 1)
        self.flankASize = QtWidgets.QLineEdit(self.cassetteDesign)
        self.flankASize.setMaximumSize(QtCore.QSize(100, 20))
        self.flankASize.setCursorPosition(3)
        self.flankASize.setObjectName("flankASize")
        self.gridLayout.addWidget(self.flankASize, 0, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.cassetteDesign)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.circularTargetCheck = QtWidgets.QCheckBox(self.cassetteDesign)
        self.circularTargetCheck.setObjectName("circularTargetCheck")
        self.verticalLayout_6.addWidget(self.circularTargetCheck)
        self.cassetteMsgBox = QtWidgets.QTextEdit(self.cassetteDesign)
        self.cassetteMsgBox.setEnabled(True)
        self.cassetteMsgBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cassetteMsgBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cassetteMsgBox.setReadOnly(True)
        self.cassetteMsgBox.setObjectName("cassetteMsgBox")
        self.verticalLayout_6.addWidget(self.cassetteMsgBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.tabWidget.addTab(self.cassetteDesign, "")
        self.workingProtocol = QtWidgets.QWidget()
        self.workingProtocol.setObjectName("workingProtocol")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.workingProtocol)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 801, 440))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_46 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_7.addWidget(self.label_46)
        self.label_44 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_7.addWidget(self.label_44)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.primerList = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primerList.sizePolicy().hasHeightForWidth())
        self.primerList.setSizePolicy(sizePolicy)
        self.primerList.setMinimumSize(QtCore.QSize(0, 280))
        self.primerList.setMaximumSize(QtCore.QSize(16777215, 280))
        self.primerList.setObjectName("primerList")
        self.verticalLayout_8.addWidget(self.primerList)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_8.addWidget(self.label_26)
        self.insertStyleSwapper = QtWidgets.QStackedWidget(self.verticalLayoutWidget_2)
        self.insertStyleSwapper.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertStyleSwapper.sizePolicy().hasHeightForWidth())
        self.insertStyleSwapper.setSizePolicy(sizePolicy)
        self.insertStyleSwapper.setMinimumSize(QtCore.QSize(0, 100))
        self.insertStyleSwapper.setMaximumSize(QtCore.QSize(16777215, 100))
        self.insertStyleSwapper.setObjectName("insertStyleSwapper")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(30, 40, 231, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setGeometry(QtCore.QRect(30, 30, 31, 20))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(60, 30, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(44, 20, 51, 14))
        self.label_7.setObjectName("label_7")
        self.line_3 = QtWidgets.QFrame(self.page)
        self.line_3.setGeometry(QtCore.QRect(420, 40, 191, 16))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.page)
        self.line_4.setGeometry(QtCore.QRect(250, 30, 31, 16))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(280, 30, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line_5 = QtWidgets.QFrame(self.page)
        self.line_5.setGeometry(QtCore.QRect(250, 50, 31, 16))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(244, 50, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_6 = QtWidgets.QFrame(self.page)
        self.line_6.setGeometry(QtCore.QRect(570, 50, 31, 16))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(564, 50, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setGeometry(QtCore.QRect(260, 60, 51, 14))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setGeometry(QtCore.QRect(260, 20, 51, 14))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(584, 60, 51, 14))
        self.label_13.setObjectName("label_13")
        self.line_13 = QtWidgets.QFrame(self.page)
        self.line_13.setGeometry(QtCore.QRect(390, 50, 31, 16))
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setObjectName("line_13")
        self.label_22 = QtWidgets.QLabel(self.page)
        self.label_22.setGeometry(QtCore.QRect(420, 50, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page)
        self.label_23.setGeometry(QtCore.QRect(400, 60, 51, 14))
        self.label_23.setObjectName("label_23")
        self.line_14 = QtWidgets.QFrame(self.page)
        self.line_14.setGeometry(QtCore.QRect(396, 30, 31, 16))
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setObjectName("line_14")
        self.label_24 = QtWidgets.QLabel(self.page)
        self.label_24.setGeometry(QtCore.QRect(406, 20, 51, 14))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.page)
        self.label_25.setGeometry(QtCore.QRect(390, 30, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.line_15 = QtWidgets.QFrame(self.page)
        self.line_15.setGeometry(QtCore.QRect(270, 40, 141, 16))
        self.line_15.setStyleSheet("color: rgb(0, 170, 0);")
        self.line_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_15.setLineWidth(2)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setObjectName("line_15")
        self.label_35 = QtWidgets.QLabel(self.page)
        self.label_35.setGeometry(QtCore.QRect(130, 20, 59, 14))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page)
        self.label_36.setGeometry(QtCore.QRect(490, 20, 59, 14))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.page)
        self.label_37.setGeometry(QtCore.QRect(320, 20, 59, 14))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.page)
        self.label_38.setGeometry(QtCore.QRect(200, 0, 71, 16))
        self.label_38.setObjectName("label_38")
        self.line_17 = QtWidgets.QFrame(self.page)
        self.line_17.setGeometry(QtCore.QRect(250, 70, 361, 16))
        self.line_17.setStyleSheet("color: rgb(240, 0, 0);")
        self.line_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_17.setLineWidth(2)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setObjectName("line_17")
        self.label_39 = QtWidgets.QLabel(self.page)
        self.label_39.setGeometry(QtCore.QRect(380, 80, 71, 16))
        self.label_39.setObjectName("label_39")
        self.line_16 = QtWidgets.QFrame(self.page)
        self.line_16.setGeometry(QtCore.QRect(30, 10, 381, 16))
        self.line_16.setStyleSheet("color: rgb(240, 0, 0);")
        self.line_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_16.setLineWidth(2)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setObjectName("line_16")
        self.insertStyleSwapper.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.line_7 = QtWidgets.QFrame(self.page_2)
        self.line_7.setGeometry(QtCore.QRect(566, 60, 31, 16))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.page_2)
        self.line_8.setGeometry(QtCore.QRect(300, 40, 31, 16))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setGeometry(QtCore.QRect(580, 70, 51, 14))
        self.label_14.setObjectName("label_14")
        self.line_9 = QtWidgets.QFrame(self.page_2)
        self.line_9.setGeometry(QtCore.QRect(300, 60, 31, 16))
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(560, 60, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(330, 40, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setGeometry(QtCore.QRect(310, 30, 51, 14))
        self.label_17.setObjectName("label_17")
        self.line_10 = QtWidgets.QFrame(self.page_2)
        self.line_10.setGeometry(QtCore.QRect(30, 40, 31, 16))
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setObjectName("line_10")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(310, 70, 51, 14))
        self.label_18.setObjectName("label_18")
        self.line_11 = QtWidgets.QFrame(self.page_2)
        self.line_11.setGeometry(QtCore.QRect(320, 50, 281, 16))
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setObjectName("line_11")
        self.label_19 = QtWidgets.QLabel(self.page_2)
        self.label_19.setGeometry(QtCore.QRect(60, 40, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_2)
        self.label_20.setGeometry(QtCore.QRect(40, 30, 51, 14))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_2)
        self.label_21.setGeometry(QtCore.QRect(294, 60, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.line_12 = QtWidgets.QFrame(self.page_2)
        self.line_12.setGeometry(QtCore.QRect(30, 50, 281, 16))
        self.line_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setObjectName("line_12")
        self.label_33 = QtWidgets.QLabel(self.page_2)
        self.label_33.setGeometry(QtCore.QRect(150, 20, 59, 14))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.page_2)
        self.label_34.setGeometry(QtCore.QRect(430, 20, 59, 14))
        self.label_34.setObjectName("label_34")
        self.insertStyleSwapper.addWidget(self.page_2)
        self.verticalLayout_8.addWidget(self.insertStyleSwapper)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem6)
        self.protocolSwapper = QtWidgets.QStackedWidget(self.workingProtocol)
        self.protocolSwapper.setGeometry(QtCore.QRect(0, 430, 801, 431))
        self.protocolSwapper.setObjectName("protocolSwapper")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.protocol_deletion = QtWidgets.QTextEdit(self.page_3)
        self.protocol_deletion.setGeometry(QtCore.QRect(0, 0, 801, 421))
        self.protocol_deletion.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.protocol_deletion.setFrameShadow(QtWidgets.QFrame.Plain)
        self.protocol_deletion.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.protocol_deletion.setObjectName("protocol_deletion")
        self.protocolSwapper.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.protocol_insertion = QtWidgets.QTextEdit(self.page_4)
        self.protocol_insertion.setEnabled(True)
        self.protocol_insertion.setGeometry(QtCore.QRect(0, 0, 801, 421))
        self.protocol_insertion.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.protocol_insertion.setFrameShadow(QtWidgets.QFrame.Plain)
        self.protocol_insertion.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.protocol_insertion.setObjectName("protocol_insertion")
        self.protocolSwapper.addWidget(self.page_4)
        self.tabWidget.addTab(self.workingProtocol, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        CutSPR.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CutSPR)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 20))
        self.menubar.setObjectName("menubar")
        self.menuBLAST_config = QtWidgets.QMenu(self.menubar)
        self.menuBLAST_config.setObjectName("menuBLAST_config")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        CutSPR.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CutSPR)
        self.statusbar.setObjectName("statusbar")
        CutSPR.setStatusBar(self.statusbar)
        self.actionBLAST_executables = QtWidgets.QAction(CutSPR)
        self.actionBLAST_executables.setObjectName("actionBLAST_executables")
        self.actionHow_to_use = QtWidgets.QAction(CutSPR)
        self.actionHow_to_use.setObjectName("actionHow_to_use")
        self.actionContact = QtWidgets.QAction(CutSPR)
        self.actionContact.setObjectName("actionContact")
        self.actionQuit = QtWidgets.QAction(CutSPR)
        self.actionQuit.setObjectName("actionQuit")
        self.menuBLAST_config.addAction(self.actionBLAST_executables)
        self.menuBLAST_config.addSeparator()
        self.menuBLAST_config.addAction(self.actionQuit)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionContact)
        self.menubar.addAction(self.menuBLAST_config.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(CutSPR)
        self.tabWidget.setCurrentIndex(0)
        self.insertStyleSwapper.setCurrentIndex(1)
        self.protocolSwapper.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CutSPR)

    def retranslateUi(self, CutSPR):
        _translate = QtCore.QCoreApplication.translate
        CutSPR.setWindowTitle(_translate("CutSPR", "CutSPR"))
        self.textBrowser.setHtml(_translate("CutSPR", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Welcome</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Thank you for using CutSPR. This Tool allows you to design all primers needed to create a specific CRISPR-Cas9 based vector for the engineering of <span style=\" font-style:italic;\">B. subtilis </span>or its viruses. The generated primers are designated for the use with the pJOE8999 plasmid system created by Dr. Josef Altenbuchner. It may also be helpful with similar systems as most parameters can be freely modified.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.sgRNAHeader.setText(_translate("CutSPR", "1. sgRNA Spacer Sequence"))
        self.sgRNAdesc.setHtml(_translate("CutSPR", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">sgRNA Spacer Sequence</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Provided with the genome sequences of the host, the virus (if any), and the gene locus to be edited, CutSPR finds unique spacer sequences. Candidates are verified against the genetic background to ensure specificity to the desired target. After selection of the desired spacer sequence CutSPR generates primers for the creation of a specific sgRNA. The PAM sequence, spacer length and primer extension can be freely modified, which may be of interest for systems different from the designated. </p></body></html>"))
        self.indelCassHeader.setText(_translate("CutSPR", "2. Deletion or Insertion Cassette"))
        self.indelCassDesc.setHtml(_translate("CutSPR", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Deletion- or Insertion-Cassette</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">A recombination cassette is designed from the genomic surrounding of the deletion target. In case an insertion is required a desired sequence can be provided. CutSPR generates all required primers and extends them with homolog regions to allow fusing of the fragments via PCR. The exterior primers of the recombination cassette are extended with restriction sides to enable cloning in to the SfiI processed vector. The size of each flank and the extensions of the outer primers can be freely modified.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.vecConstHeader.setText(_translate("CutSPR", "3. Vector Construction"))
        self.vecConstDesc.setHtml(_translate("CutSPR", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Vector Construction</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">After all parameters are defined CutSPR will provide working instructions of how to use the generated primers and create the desired CRISPR-Cas9 base mutagenesis vector. It will also give information on how to introduce this vector to the working strain <span style=\" font-style:italic;\">B. subtilis</span> TS01 and create the desired mutant.</p></body></html>"))
        self.label_29.setText(_translate("CutSPR", "For more information about this application, please visit:"))
        self.label_31.setText(_translate("CutSPR", "<html><head/><body><p><a href=\"https://github.com/sdietri/cutspr\"><span style=\" text-decoration: underline; color:#0000ff;\">CutSPR GitHub</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IntroductionPage), _translate("CutSPR", "Welcome"))
        self.label_3.setText(_translate("CutSPR", "Reference genome (host and virus) as GBK, fasta or EMBL:"))
        self.fileSelectionButton.setText(_translate("CutSPR", "Select Files..."))
        self.label_4.setText(_translate("CutSPR", "Deletion target sequence:"))
        self.label.setText(_translate("CutSPR", "PAM pattern"))
        self.PAMpattern.setText(_translate("CutSPR", "NGG"))
        self.label_30.setText(_translate("CutSPR", "Spacer in bp:"))
        self.targetLength.setInputMask(_translate("CutSPR", "99"))
        self.targetLength.setText(_translate("CutSPR", "20"))
        self.cutRun.setText(_translate("CutSPR", "Search Spacer Sequence"))
        self.label_2.setText(_translate("CutSPR", "Select desired spacer sequence from results:"))
        self.label_43.setText(_translate("CutSPR", "Sequence and GC content"))
        self.label_42.setText(_translate("CutSPR", "Percent similarity of next best off-target"))
        self.label_45.setText(_translate("CutSPR", "Potential Seeds in Reference"))
        self.cloningSitesgRNA.setText(_translate("CutSPR", "Choose cloning sites"))
        self.label_27.setText(_translate("CutSPR", "Default vector pJOE8999 (change if necessary)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gsRNAsearch), _translate("CutSPR", "1. sgRNA Spacer Sequence"))
        self.label_5.setText(_translate("CutSPR", "Enter sequence to insert (optional):"))
        self.cloningSiteRecomb.setText(_translate("CutSPR", "Choose cloning restriction site"))
        self.label_28.setText(_translate("CutSPR", "Default vector pJOE8999 (change if necessary)"))
        self.label_32.setText(_translate("CutSPR", "Flank sizes (bases)"))
        self.flankBSize.setInputMask(_translate("CutSPR", "9999"))
        self.flankBSize.setText(_translate("CutSPR", "700"))
        self.label_40.setText(_translate("CutSPR", "FlankA target size"))
        self.flankASize.setInputMask(_translate("CutSPR", "9999"))
        self.flankASize.setText(_translate("CutSPR", "700"))
        self.label_41.setText(_translate("CutSPR", "FlankB target size"))
        self.circularTargetCheck.setText(_translate("CutSPR", "Is target replicon circular?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cassetteDesign), _translate("CutSPR", "2. Deletion or Insertion Cassette"))
        self.label_46.setText(_translate("CutSPR", "Sequence"))
        self.label_44.setText(_translate("CutSPR", "Melting temp. in °C (overhang | primer)"))
        self.label_26.setText(_translate("CutSPR", "        1,2: sgRNA primer"))
        self.label_6.setText(_translate("CutSPR", ">"))
        self.label_7.setText(_translate("CutSPR", "3"))
        self.label_8.setText(_translate("CutSPR", ">"))
        self.label_9.setText(_translate("CutSPR", "<"))
        self.label_10.setText(_translate("CutSPR", "<"))
        self.label_11.setText(_translate("CutSPR", "4"))
        self.label_12.setText(_translate("CutSPR", "5"))
        self.label_13.setText(_translate("CutSPR", "8"))
        self.label_22.setText(_translate("CutSPR", ">"))
        self.label_23.setText(_translate("CutSPR", "7"))
        self.label_24.setText(_translate("CutSPR", "6"))
        self.label_25.setText(_translate("CutSPR", "<"))
        self.label_35.setText(_translate("CutSPR", "FlankA"))
        self.label_36.setText(_translate("CutSPR", "FlankB"))
        self.label_37.setText(_translate("CutSPR", "Insert"))
        self.label_38.setText(_translate("CutSPR", "Fragment C"))
        self.label_39.setText(_translate("CutSPR", "Fragment D"))
        self.label_14.setText(_translate("CutSPR", "6"))
        self.label_15.setText(_translate("CutSPR", "<"))
        self.label_16.setText(_translate("CutSPR", ">"))
        self.label_17.setText(_translate("CutSPR", "5"))
        self.label_18.setText(_translate("CutSPR", "4"))
        self.label_19.setText(_translate("CutSPR", ">"))
        self.label_20.setText(_translate("CutSPR", "3"))
        self.label_21.setText(_translate("CutSPR", "<"))
        self.label_33.setText(_translate("CutSPR", "FlankA"))
        self.label_34.setText(_translate("CutSPR", "FlankB"))
        self.protocol_deletion.setHtml(_translate("CutSPR", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%; page-break-before:always;\"><span style=\" font-family:\'Cambria,serif\'; font-size:14pt; font-weight:600; color:#000000;\">Vector Construction (Deletion)</span></p>\n"
"<p style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Note</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">We will not present exact recipes for the mentioned enzymatic reactions, PCRs or purification steps, as many paths lead to success. Thus, we recommend to study and accurately follow the manufacturer’s instructions of the enzymes and kits present in your lab.</p>\n"
"<p style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Cloning the sgRNA</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Adjust primer 1 and 2 to a final concentration of 5 µM. Mix 10 µl of each primer and incubate for 30-60 min at room temperature. Digest ~1 µg of empty vector with BsaI endonuclease. It will result in two fragments. One with a size of ~7.4 kb and another with 371 bp. Purify the bigger fragment via gel-extraction. Ligate about 40 ng of the prepared vector with 1 µl of the primer hybridization using T4-DNA-Ligase. Use the ligation reaction to directly transform chemical competent <span style=\" font-style:italic;\">E. coli</span> cells and select clones on LB agar plates supplemented with 25-50 µg/ml Kanamycin. Verify your new constructs via restriction analysis with the endonuclease EcoRI or BsaI. In case of an empty vector EcoRI will result in three fragments (~3.2 kb, ~4 kb and 200 bp), whereas BsaI will result in two as described above. In case of the desired construct EcoRI digestion results in two fragments (~3 kb and 4 kb) and BsaI has no effect. Positive candidates can be further verified via Sanger sequencing using primer RH003 (5’ACCGAGCGTTCTGAACAAATCC).</p>\n"
"<p style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Cloning the Deletion-Cassette</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Amplify the flanks of the target locus by PCR with the respective primers (Primer3 and Primer4 for Flank A<span style=\" color:#0070c0;\"> </span><span style=\" color:#000000;\">and Primer 5 and Primer 6 for Flank B</span>) from your target genome, setting the annealing temperature to 54°C. Use a high fidelity DNA polymerase with proof-reading activity. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Verify your PCR products via agarose gel electrophoresis and purify them. Dilute the DNA to a concentration of 0.1 ng/µl. Mix 10 µl of each diluted amplification product and use 1 µl of this mixture as template for PCR with Primer 3 and Primer <span style=\" color:#000000;\">6</span> to create the <span style=\" color:#000000;\">deletion</span><span style=\" color:#0070c0;\">-</span>cassette. Set the annealing temperature to 54°C. Verify the PCR product via gel-electrophoresis. It should reveal a combined product size of both flanks. Purify the PCR product and digest it with SfiI endonuclease. In parallel digest the sgRNA containing vector with SfiI. Purify the linearized 7.4 kb vector via gel- extraction. Use 40 ng of the processed vector and ligate it with the deletion cassette using the T4-DNA-Ligase (~<span style=\" color:#000000;\">40</span> ng in case of a ~<span style=\" color:#000000;\">1</span>.5 kb <span style=\" color:#000000;\">deletion</span>-cassette). Use the ligation reaction to directly transform chemically competent <span style=\" font-style:italic;\">E. coli</span> cells and select clones on LB agar plates supplemented with 25-50 µg/ml Kanamycin. Verify your new constructs via restriction analysis with the endonuclease SalI-XbaI or SfiI. A positive construct should release the recombination-cassette, visible as a separate band in an agarose gel. Verify sequence of your deletion cassette via Sanger sequencing using primer RH001 (<span style=\" font-size:10pt;\">AGCTTAGGCCCAGTCGAAAG</span>), RH002 (<span style=\" font-size:10pt;\">CAGCTAGGAGGTGACTGAAG</span>) and if necessary further primer used for construction.</p>\n"
"<p style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Transformation of </span><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; font-style:italic; color:#000000;\">B. subtilis</span><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\"> TS01</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Inoculate a 10 ml LB medium in a 100 ml conical flask to an OD<span style=\" vertical-align:sub;\">600</span> of 0.1 with an overnight culture of <span style=\" font-style:italic;\">B. subtilis</span> TS01 and incubate it at 37°C for 90 min under vigorous shaking. Subsequently supplement the culture with <span style=\" font-variant:small-caps;\">d</span>-mannitol to a final concentration of 0.5% (w/v) and culture it for further 90 min. Pellet cell at 3500 g and 4°C for 5 min and wash them twice with 10 ml of ice cold LB medium. Set the cell suspension to an OD<span style=\" vertical-align:sub;\">600</span> of 0.5. Mix vector DNA (100 ng) with 1 ml of competent cells in a 15 ml sterile tube and incubate for 60 min at 30°C on a roller drum. Plate cells on selective LB agar plates supplemented with 25 µg/ml Kanamycin and incubate for ~16 h at 30°C.</p>\n"
"<p style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Phage genetic modification</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Culture a clone of <span style=\" font-style:italic;\">B. subtilis</span> TS01 harboring a CRISPR-Cas9 mutagenesis vector in liquid LB medium supplemented with 25 µg/ml Kanamycin for ~16 h. Incubate 100 µl of cells with 100 µl phage suspension for 5 min to ensure infection, mix with 2 ml pre-warmed (50°C) overlay agar and plate on LB medium plates supplemented with D-mannose (0.2% w/v). Pick a few resulting plaques with a sterile toothpick and placed into 500 µl sterile LB medium for 10 min. Use this phage suspensions for a plaque assay with <span style=\" font-style:italic;\">B. subtilis</span> TS01 to achieve further separation of the isolates. Pick a few plaques again and generate LB phage suspension. Use 1 µl of these suspensions as template for PCR with Primer 3 and Primer 6. Set the annealing temperature to 54°C. Verify the PCR product via gel-electrophoresis and select the clone with the desired genotype.</p></body></html>"))
        self.protocol_insertion.setHtml(_translate("CutSPR", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%; page-break-before:always;\"><span style=\" font-family:\'Cambria,serif\'; font-size:14pt; font-weight:600; color:#000000;\">Vector Construction (Insertion)</span></p>\n"
"<p style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Note</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">We will not present exact recipes for the mentioned enzymatic reactions, PCRs or purification steps, as many paths lead to success. Thus, we recommend to study and accurately follow the manufacturer’s instructions of the enzymes and kits present in your lab.</p>\n"
"<p style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Cloning the sgRNA</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Adjust primer 1 and 2 to a final concentration of 5 µM. Mix 10 µl of each primer and incubate for 30-60 min at room temperature. Digest ~1 µg of empty vector with BsaI endonuclease. It will result in two fragments. One with a size of ~7.4 kb and another with 371 bp. Purify the bigger fragment via gel-extraction. Ligate about 40 ng of the prepared vector with 1 µl of the primer hybridization using T4-DNA-Ligase. Use the ligation reaction to directly transform chemical competent <span style=\" font-style:italic;\">E. coli</span> cells and select clones on LB agar plates supplemented with 25-50 µg/ml Kanamycin. Verify your new constructs via restriction analysis with the endonuclease EcoRI or BsaI. In case of an empty vector EcoRI will result in three fragments (~3.2 kb, ~4 kb and 200 bp), whereas BsaI will result in two as described above. In case of the desired construct EcoRI digestion results in two fragments (~3 kb and 4 kb) and BsaI has no effect. Positive candidates can be further verified via Sanger sequencing using primer RH003 (5’ACCGAGCGTTCTGAACAAATCC).</p>\n"
"<p style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Cloning the Insertion-Cassette</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Amplify the flanks of the target locus by PCR with the respective primers (Primer3 and Primer4 for Flank A, Primer5 and Primer6 <span style=\" color:#000000;\">for insertion-fragment and Primer 7 and Primer 8 for Flank B</span>) from your target genome, setting the annealing temperature to 54°C. Use a high fidelity DNA polymerase with proof-reading activity. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Verify your PCR products via agarose gel electrophoresis and purify them. Dilute the DNA to a concentration of 0.1 ng/µl. Mix 10 µl of each diluted amplification product and use 1 µl of this mixture as template for PCR with Primer 3 and Primer <span style=\" color:#000000;\">8</span> to create the <span style=\" color:#000000;\">insertion</span><span style=\" color:#0070c0;\">-</span>cassette. Set the annealing temperature to 54°C. Verify the PCR product via gel-electrophoresis. It should reveal a combined product size of both flanks <span style=\" color:#000000;\">and the insertion-fragment</span>. Purify the PCR product and digest it with SfiI endonuclease. In parallel digest the sgRNA containing vector with SfiI. Purify the linearized 7.4 kb vector via gel- extraction. Use 40 ng of the processed vector and ligate it with the <span style=\" color:#000000;\">insertion</span>-cassette using the T4-DNA-Ligase (~<span style=\" color:#000000;\">60</span> ng in case of a ~<span style=\" color:#000000;\">2</span>.5 kb <span style=\" color:#000000;\">insertion</span>-cassette). Use the ligation reaction to directly transform chemically competent <span style=\" font-style:italic;\">E. coli</span> cells and select clones on LB agar plates supplemented with 25-50 µg/ml Kanamycin. Verify your new constructs via restriction analysis with the endonuclease SalI-XbaI or SfiI. A positive construct should release the recombination-cassette, visible as a separate band in an agarose gel. Verify sequence of your deletion cassette via Sanger sequencing using primer RH001 (<span style=\" font-size:10pt;\">AGCTTAGGCCCAGTCGAAAG</span>), RH002 (<span style=\" font-size:10pt;\">CAGCTAGGAGGTGACTGAAG</span>) and if necessary further primer used for construction.</p>\n"
"<p style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Transformation of </span><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; font-style:italic; color:#000000;\">B. subtilis</span><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\"> TS01</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Inoculate a 10 ml LB medium in a 100 ml conical flask to an OD<span style=\" vertical-align:sub;\">600</span> of 0.1 with an overnight culture of <span style=\" font-style:italic;\">B. subtilis</span> TS01 and incubate it at 37°C for 90 min under vigorous shaking. Subsequently supplement the culture with <span style=\" font-variant:small-caps;\">d</span>-mannitol to a final concentration of 0.5% (w/v) and culture it for further 90 min. Pellet cell at 3500 g and 4°C for 5 min and wash them twice with 10 ml of ice cold LB medium. Set the cell suspension to an OD<span style=\" vertical-align:sub;\">600</span> of 0.5. Mix vector DNA (100 ng) with 1 ml of competent cells in a 15 ml sterile tube and incubate for 60 min at 30°C on a roller drum. Plate cells on selective LB agar plates supplemented with 25 µg/ml Kanamycin and incubate for ~16 h at 30°C.</p>\n"
"<p style=\" margin-top:16px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Cambria,serif\'; font-size:13pt; font-weight:600; color:#000000;\">Phage genetic modification</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%;\">Culture a clone of <span style=\" font-style:italic;\">B. subtilis</span> TS01 harboring a CRISPR-Cas9 mutagenesis vector in liquid LB medium supplemented with 25 µg/ml Kanamycin for ~16 h. Incubate 100 µl of cells with 100 µl phage suspension for 5 min to ensure infection, mix with 2 ml pre-warmed (50°C) overlay agar and plate on LB medium plates supplemented with D-mannose (0.2% w/v). Pick a few resulting plaques with a sterile toothpick and placed into 500 µl sterile LB medium for 10 min. Use this phage suspensions for a plaque assay with <span style=\" font-style:italic;\">B. subtilis</span> TS01 to achieve further separation of the isolates. Pick a few plaques again and generate LB phage suspension. Use 1 µl of these suspensions as template for PCR with Primer 3 and Primer <span style=\" color:#000000;\">8</span>. Set the annealing temperature to 54°C. Verify the PCR product via gel-electrophoresis and select the clone with the desired genotype.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.workingProtocol), _translate("CutSPR", "3. Vector Construction"))
        self.menuBLAST_config.setTitle(_translate("CutSPR", "Menu"))
        self.menuHelp.setTitle(_translate("CutSPR", "About"))
        self.actionBLAST_executables.setText(_translate("CutSPR", "BLAST executables"))
        self.actionHow_to_use.setText(_translate("CutSPR", "Reference/Citing"))
        self.actionContact.setText(_translate("CutSPR", "Contact"))
        self.actionQuit.setText(_translate("CutSPR", "Quit"))

from .cqlabel import CQlabel
